apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    service: reverseproxy
spec:
  selector:
    matchLabels:
      service: reverseproxy
  replicas: 1
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
        - image: cjs10lib/reverseproxy:0.0.1
          name: reverseproxy
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
