language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed cjs10lib/udagram-api-feed:0.0.1
  - docker tag udagram-api-user cjs10lib/udagram-api-user:0.0.1
  - docker tag udagram-frontend cjs10lib/udagram-frontend:0.0.1
  - docker tag reverseproxy cjs10lib/reverseproxy:0.0.1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push cjs10lib/udagram-api-feed:0.0.1
  - docker push cjs10lib/udagram-api-user:0.0.1
  - docker push cjs10lib/udagram-frontend:0.0.1
  - docker push cjs10lib/udagram-reverseproxy:0.0.1