apiVersion: v1
kind: Service
metadata:
  name: api-user
  labels:
    service: api-user
    app: api-user
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: api-user
  type: ClusterIP
