apiVersion: v1
kind: Service
metadata:
  name: api-feed
  labels:
    service: api-feed
    app: api-feed
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: api-feed
  type: ClusterIP
status:
  loadBalancer: {}
